kind: Namespace
apiVersion: v1
metadata:
  name: emily
  labels:
    app.kubernetes.io/name: namespace

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-favourite-tree
  namespace: emily
  labels:
    app.kubernetes.io/name: favourite-tree
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: favourite-tree
  template:
    metadata:
      labels:
        app.kubernetes.io/name: favourite-tree
    spec:
      containers:
      - name: my-favourite-tree
        image: my-favourite-tree:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: favourite-tree-svc
  namespace: emily
  labels:
    app.kubernetes.io/name: favourite-tree
spec:
  type: NodePort
  ports:
    - port: 5000
  selector:
    app.kubernetes.io/name: favourite-tree

---

kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: favourite-tree-ingress
  namespace: emily
spec:
  rules:
  - host: local.emilywoods.me
    http:
      paths:
      - backend:
          serviceName: favourite-tree-svc
          servicePort: 5000
